/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ChessChaturanga.Visual;
import com.sun.awt.AWTUtilities; 

import java.awt.Shape; 
import java.awt.geom.Ellipse2D;
import java.awt.geom.RoundRectangle2D;
import javax.swing.JFrame;

/**
 *
 * @author dmenjivar
 */
public class Menu extends javax.swing.JFrame {
    
    /**
     * Creates new form Menu
     */
    public Menu() {
        setUndecorated(true) ; //Quitamos el borde de las jframe
        setOpacity(0.8f);//con la f aclaramos que es float 
        initComponents();
        setLocationRelativeTo(null); // Ponemos en el centro la jframe
        Shape forma = new RoundRectangle2D.Double(0, 0, this.getBounds().width, this.getBounds().height, 30, 30);
        //Shape forma =  new Ellipse2D.Float(0,0,getWidth(),getHeight()); 
        AWTUtilities.setWindowShape(this, forma)  ; 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Btn_Salir = new javax.swing.JButton();
        Btn_IniciarSesion = new javax.swing.JButton();
        Btn_CrearUsuario = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Chess Chaturanga");
        setPreferredSize(new java.awt.Dimension(760, 430));
        setResizable(false);
        getContentPane().setLayout(null);

        Btn_Salir.setText("Salir");
        Btn_Salir.setOpaque(false);
        Btn_Salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_SalirActionPerformed(evt);
            }
        });
        getContentPane().add(Btn_Salir);
        Btn_Salir.setBounds(260, 260, 260, 40);

        Btn_IniciarSesion.setText("Iniciar sesión");
        Btn_IniciarSesion.setOpaque(false);
        Btn_IniciarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_IniciarSesionActionPerformed(evt);
            }
        });
        getContentPane().add(Btn_IniciarSesion);
        Btn_IniciarSesion.setBounds(260, 120, 260, 40);

        Btn_CrearUsuario.setText("Crear usuario");
        Btn_CrearUsuario.setOpaque(false);
        Btn_CrearUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_CrearUsuarioActionPerformed(evt);
            }
        });
        getContentPane().add(Btn_CrearUsuario);
        Btn_CrearUsuario.setBounds(260, 190, 260, 40);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ChessChaturanga/Assets/vintage-chess-pieces-20736-1920x1080.jpg"))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 0, 770, 430);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Btn_SalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_SalirActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_Btn_SalirActionPerformed

    private void Btn_CrearUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_CrearUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Btn_CrearUsuarioActionPerformed

    private void Btn_IniciarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_IniciarSesionActionPerformed
        Login Log = new Login();
        this.setVisible(false);
        Log.setVisible(true);
    }//GEN-LAST:event_Btn_IniciarSesionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Btn_CrearUsuario;
    private javax.swing.JButton Btn_IniciarSesion;
    private javax.swing.JButton Btn_Salir;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
